version: "3.8"

services:
  db:
    image: mongo:4.2
    environment:
      MONGO_INITDB_DATABASE: app
    ports:
      - 27017:27017
    networks:
      - default
  app:
    build:
      dockerfile: .docker/app/Dockerfile
      context: .
    ports:
      - 80:80
    command: php -S 0.0.0.0:80 -t public
    depends_on:
      - db
    networks:
      - default
    volumes:
      - .:/var/www/app:cached
      - ./vendor:/var/www/app/vendor:delegated
      - ./var:/var/www/app/var:delegated

networks:
  default: ~
