version: "3.8"

services:
  db:
    image: mongo:4.2
    environment:
      MONGO_INITDB_DATABASE: app
    ports:
      - 27017:27017
    networks:
      - default
  app:
    restart: on-failure
    build: .
    ports:
      - 80:80
      - 9229:9229
    depends_on:
      - db
    networks:
      - default
    volumes:
      - .:/var/www/app/:cached
      - /var/www/app/node_modules/

networks:
  default: ~
